### ISSUE TITLE
More structured command line module help

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdacli#34]
Our argument parser

https://github.com/MDAnalysis/mdacli/blob/78fa3f2fff31fb7f9acf71ee8811ab902369e947/src/mdacli/cli.py#L60

has creates the groups `Common Analysis Parameters`, `Mandatory Parameters` and `Optional Parameters` when the help page is accessed.
We should split `Common Analysis Parameters` into something like `Universe Parameters`, `Run Parameters` and `Storing Results Parameters` to be more structured. Additionally, we should give informations on how we store the results after the analysis at the beginning of the `Storing Results Parameters` group.

**Comment by joaomcteixeira** [comment]
> Additionally, we should give informations on how we store the results after the analysis at the beginning of the Storing Results Parameters group.

That might be a problem because there can be several saving possibilities. If the Analysis class as a `save_results` method, `mdacli` won't know how the class will save the results. Therefore, you can't write an help statement because we can't know if it will happen.

We can add very detailed information on the main DOCUMENTATION of the project (readthedocs) about how we save the results in case `save_results()` methods is not present. And then redirect the CLI user to the DOC page. We should explain in the `mdacli -h` but not overload it.
